title: Imanol Herrero
description: Software engineer with 4 years of professional experience developing robust backends and dynamic frontends for startups and enterprises.

# Posts get URLs like /ideas/post-slug.html
permalink: /ideas/:slug.html

# Don't include these in the build output
exclude:
  - README.md
  - .gitignore
